version: '3'

services:

  reverse-proxy: 
    image: nginx:1.15.8
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    links:
      - "frontend"
      - "backend"

  frontend:
    image: surl_frontend
    ports:
      - "3000:3000"

  backend:
    image: surl_backend
    ports:
      - "4000:4000"
    links:
      - "database"

  database:
    image: mongo:4.1.6
    ports:
      - "27017:27017"